### ISSUE TITLE
Yum pkg command failing

### ISSUE THREAD

**Issue by rossedman** [geerlingguy/ansible-role-packer-rhel#7]
I don't think `yum: pkg=` is supported anymore. I am receiving failures from this [line](https://github.com/geerlingguy/ansible-role-packer-rhel/blob/master/tasks/main.yml#L8). Am I confused about this? I thought this should be like this:

```
- name: Ensure necessary packages are installed.
  yum: name="{{ item }}" state=installed
  with_items:
    - wget
    - perl
    - cpp
    - gcc
    - make
    - bzip2
    - kernel-headers
    - kernel-devel
    - "kernel-devel-{{ kernel_release.stdout }}"
    - libselinux-python
```
